"""CSV table schemas, PK/FK, enums. Canonical Systimo store."""

from __future__ import annotations

TABLES: dict[str, tuple[str, ...]] = {
    "systems": (
        "system_id",
        "name",
        "product_name",
        "domain",
        "status",
        "owner_type",
        "backend_package",
        "frontend_path",
        "frontend_url",
        "api_namespace",
        "data_roots",
        "execution_capable",
        "canonical_role",
        "description",
        "momento_system_id",
    ),
    "connections": (
        "connection_id",
        "source_system_id",
        "target_system_id",
        "connection_type",
        "source_interface",
        "target_interface",
        "transport",
        "direction",
        "schema_version",
        "environment",
        "data_mode",
        "lifecycle",
        "health",
        "permission",
        "capability",
        "adapter",
        "expected_lock",
        "last_check_at",
        "last_success_at",
        "last_failure_at",
        "latency_ms",
        "reason",
        "notes",
    ),
    "interfaces": (
        "interface_id",
        "owner_system_id",
        "kind",
        "path",
        "capability",
        "schema_version",
        "notes",
    ),
    "datasets": (
        "dataset_id",
        "owner_system_id",
        "name",
        "universe",
        "n_expected",
        "location",
        "schema_version",
        "notes",
    ),
    "governance": (
        "governance_id",
        "resource_id",
        "resource_type",
        "owner_system_id",
        "consumer_system_id",
        "permission",
        "environment",
        "policy_source",
        "notes",
    ),
    "schemas": (
        "schema_id",
        "name",
        "version",
        "owner_system_id",
        "notes",
    ),
    "health_snapshots": (
        "snapshot_id",
        "connection_id",
        "observed_at",
        "status",
        "check_type",
        "latency_ms",
        "error_code",
        "error_message",
        "source_timestamp",
        "n_observed",
    ),
    "connection_events": (
        "event_id",
        "connection_id",
        "observed_at",
        "previous_status",
        "new_status",
        "check_type",
        "latency_ms",
        "error_code",
        "error_message",
        "source_timestamp",
    ),
    "queries": (
        "query_id",
        "query_type",
        "requested_at",
        "completed_at",
        "requested_by",
        "params_json",
        "status",
    ),
    "answers": (
        "answer_id",
        "query_id",
        "completed_at",
        "result_schema",
        "result_json",
        "warnings",
        "artifact_id",
    ),
    "sources": (
        "source_id",
        "query_id",
        "system_id",
        "interface_id",
        "schema_version",
        "provenance",
    ),
    "artifacts_index": (
        "artifact_id",
        "query_id",
        "answer_id",
        "created_at",
        "path",
        "checksum",
        "format",
        "supersedes",
        "rerun_of",
        "status",
    ),
    "actions": (
        "action_id",
        "action_type",
        "target_system",
        "target_resource",
        "reason",
        "source_answer_id",
        "dry_run_supported",
        "approval_required",
        "risk_class",
        "handler",
        "status",
    ),
    "action_runs": (
        "run_id",
        "action_id",
        "started_at",
        "finished_at",
        "mode",
        "status",
        "error",
        "result_json",
    ),
    "agents": (
        "agent_id",
        "name",
        "role",
        "enabled",
        "allowed_query_scopes",
        "allowed_action_types",
        "requires_approval",
        "implementation",
        "version",
    ),
    "agent_runs": (
        "run_id",
        "agent_id",
        "started_at",
        "finished_at",
        "query_ids",
        "artifact_ids",
        "proposed_action_ids",
        "applied_action_ids",
        "status",
        "error",
    ),
    "transition_traces": (
        "trace_id",
        "trade_id",
        "internal_game_id",
        "event_id",
        "A_contract",
        "B_contract",
        "as_of",
        "feed_mode",
        "current_stage",
        "overall_status",
        "first_seen_at",
        "last_updated_at",
        "event_count",
        "integrity_status",
        "latest_event_hash",
    ),
    "transition_events": (
        "transition_event_id",
        "trace_id",
        "stage_seq",
        "system_id",
        "object_type",
        "object_id",
        "schema_name",
        "schema_version",
        "as_of",
        "event_status",
        "payload_artifact_id",
        "source_hash",
        "previous_event_hash",
        "event_hash",
        "created_at",
    ),
    "transition_sources": (
        "source_row_id",
        "trace_id",
        "transition_event_id",
        "system_id",
        "object_type",
        "object_id",
        "schema_name",
        "source_hash",
    ),
    "quadrants": (
        "quadrant_id",
        "sport",
        "heading",
        "position",
        "state",
        "alias",
    ),
    "instances": (
        "instance_id",
        "quadrant_id",
        "system_type",
        "label",
        "interactive",
    ),
    "nodes": (
        "node_id",
        "instance_id",
        "geometry_key",
        "label_override",
    ),
    "services": (
        "service_id",
        "argv_json",
        "cwd",
        "role",
        "dependencies",
        "scope",
        "enabled",
        "autostart",
        "ownership_mode",
        "port_policy",
        "preferred_port",
        "probe_path",
        "probe_timeout_ms",
        "probe_identity",
    ),
    "service_bindings": (
        "binding_id",
        "service_id",
        "instance_id",
    ),
    "bots": (
        "bot_id",
        "sport",
        "quadrant_id",
        "owner",
        "runtime_pointer",
        "desk_instance_id",
        "verified",
    ),
}

PRIMARY_KEYS = {
    "systems": "system_id",
    "connections": "connection_id",
    "interfaces": "interface_id",
    "datasets": "dataset_id",
    "governance": "governance_id",
    "schemas": "schema_id",
    "health_snapshots": "snapshot_id",
    "connection_events": "event_id",
    "queries": "query_id",
    "answers": "answer_id",
    "sources": "source_id",
    "artifacts_index": "artifact_id",
    "actions": "action_id",
    "action_runs": "run_id",
    "agents": "agent_id",
    "agent_runs": "run_id",
    "transition_traces": "trace_id",
    "transition_events": "transition_event_id",
    "transition_sources": "source_row_id",
    "quadrants": "quadrant_id",
    "instances": "instance_id",
    "nodes": "node_id",
    "services": "service_id",
    "service_bindings": "binding_id",
    "bots": "bot_id",
}

# (table, column, parent_table)
FOREIGN_KEYS: tuple[tuple[str, str, str], ...] = (
    ("connections", "source_system_id", "systems"),
    ("connections", "target_system_id", "systems"),
    ("interfaces", "owner_system_id", "systems"),
    ("datasets", "owner_system_id", "systems"),
    ("governance", "owner_system_id", "systems"),
    ("governance", "consumer_system_id", "systems"),
    ("schemas", "owner_system_id", "systems"),
    ("health_snapshots", "connection_id", "connections"),
    ("connection_events", "connection_id", "connections"),
    ("answers", "query_id", "queries"),
    ("sources", "query_id", "queries"),
    ("sources", "system_id", "systems"),
    ("artifacts_index", "query_id", "queries"),
    ("artifacts_index", "answer_id", "answers"),
    ("action_runs", "action_id", "actions"),
    ("agent_runs", "agent_id", "agents"),
    ("transition_events", "trace_id", "transition_traces"),
    ("transition_events", "system_id", "systems"),
    ("transition_sources", "trace_id", "transition_traces"),
    ("transition_sources", "transition_event_id", "transition_events"),
    ("transition_sources", "system_id", "systems"),
)

APPEND_ONLY = frozenset(
    {"connection_events", "health_snapshots", "agent_runs", "action_runs", "transition_events", "transition_sources"}
)

TABLE_FILES = {
    "systems": ("registry", "systems.csv"),
    "connections": ("registry", "connections.csv"),
    "interfaces": ("registry", "interfaces.csv"),
    "datasets": ("registry", "datasets.csv"),
    "governance": ("registry", "governance.csv"),
    "schemas": ("registry", "schemas.csv"),
    "health_snapshots": ("state", "health_snapshots.csv"),
    "connection_events": ("state", "connection_events.csv"),
    "queries": ("queries", "queries.csv"),
    "answers": ("queries", "answers.csv"),
    "sources": ("queries", "sources.csv"),
    "artifacts_index": ("artifacts", "index.csv"),
    "actions": ("actions", "actions.csv"),
    "action_runs": ("actions", "action_runs.csv"),
    "agents": ("agents", "agents.csv"),
    "agent_runs": ("agents", "agent_runs.csv"),
    "transition_traces": ("transitions", "transition_traces.csv"),
    "transition_events": ("transitions", "transition_events.csv"),
    "transition_sources": ("transitions", "transition_sources.csv"),
    "quadrants": ("registry", "quadrants.csv"),
    "instances": ("registry", "instances.csv"),
    "nodes": ("registry", "nodes.csv"),
    "services": ("registry", "services.csv"),
    "service_bindings": ("registry", "service_bindings.csv"),
    "bots": ("registry", "bots.csv"),
}

TOPOLOGY_TABLES = (
    "quadrants",
    "instances",
    "nodes",
    "services",
    "service_bindings",
    "bots",
)

ENUMS: dict[tuple[str, str], frozenset[str]] = {
    ("connections", "lifecycle"): frozenset({"DECLARED", "IMPLEMENTED", "DEPRECATED", "DISABLED"}),
    ("connections", "health"): frozenset(
        {"HEALTHY", "DEGRADED", "UNAVAILABLE", "MISCONFIGURED", "STALE", "UNKNOWN"}
    ),
    ("connections", "permission"): frozenset({"READ", "QUERY", "WRITE", "CONTROL", "DENY"}),
    ("transition_traces", "integrity_status"): frozenset(
        {"VERIFIED", "HASH_MISMATCH", "TRANSITION_INTEGRITY_ERROR", "UNAVAILABLE", ""}
    ),
    ("connections", "direction"): frozenset({"READ", "WRITE", "CONTROL"}),
    ("governance", "permission"): frozenset({"READ", "QUERY", "WRITE", "CONTROL", "DENY"}),
    ("systems", "execution_capable"): frozenset({"true", "false"}),
    ("services", "enabled"): frozenset({"true", "false"}),
    ("services", "autostart"): frozenset({"true", "false"}),
    ("services", "ownership_mode"): frozenset({"managed", "shared", "external", "unmanaged"}),
    ("services", "port_policy"): frozenset({"automatic", "preferred-with-fallback", "pinned"}),
    ("instances", "interactive"): frozenset({"true", "false"}),
    ("bots", "verified"): frozenset({"true", "false"}),
}
