"""Evidence and opportunity enums. Semantics are part of the contract."""

from __future__ import annotations

# Evidence
L1 = "L1_OBSERVED_STATE"
L2 = "L2_OBSERVABLE_OPPORTUNITY"
L3 = "L3_EXECUTABLE_OPPORTUNITY"
L4 = "L4_ACTUAL_EXECUTION"

# Level 2 opportunity class (primary)
NO_OBSERVATION = "NO_OBSERVATION"
EXACT_OBSERVATION = "EXACT_OBSERVATION"
BAND_OBSERVATION = "BAND_OBSERVATION"
THRESHOLD_REACHED = "THRESHOLD_REACHED"
THRESHOLD_CROSSING = "THRESHOLD_CROSSING"
GAP_THROUGH = "GAP_THROUGH"
AMBIGUOUS_SEQUENCE = "AMBIGUOUS_SEQUENCE"
INVALID_OBSERVATION = "INVALID_OBSERVATION"

# Occupancy — separate from opportunity class
OCC_EXACT = "OBSERVED_EXACT"
OCC_BAND = "OBSERVED_IN_BAND"
OCC_INFERRED = "INFERRED_POSSIBLE"
OCC_NOT = "NOT_OBSERVED"
OCC_AMBIG = "AMBIGUOUS"

# Execution models
E0 = "E0_OBSERVATION_ONLY"
E1 = "E1_CONSERVATIVE_OBSERVED_PROXY"
E2 = "E2_PARAMETERIZED_SCENARIO"
E3 = "E3_EMPIRICAL"
E4 = "E4_L2_QUEUE"
E_THEO = "E_THEORETICAL_THRESHOLD"  # illegal-promotion benchmark, labeled
E_HOLD = "E_HOLD_SETTLEMENT"
E_STOP = "E_STOP_80_40_MODEL_A"

# Payoff classes
WIN_NO_INTERVENTION = "WIN_NO_INTERVENTION"
WIN_AFTER_HEDGE = "WIN_AFTER_HEDGE"
LOSS_AFTER_HEDGE = "LOSS_AFTER_HEDGE"
STOP_LOSS = "STOP_LOSS"
PARTIAL_HEDGE = "PARTIAL_HEDGE"
GAP_MISS_FALLBACK = "GAP_MISS_FALLBACK"
NO_HEDGE_OPPORTUNITY = "NO_HEDGE_OPPORTUNITY"
AMBIGUOUS_OPPORTUNITY = "AMBIGUOUS_OPPORTUNITY"
UNRESOLVED_DATA = "UNRESOLVED_DATA"
LEAK_HOLD = "LEAK_HOLD"

NOT_AVAILABLE = "NOT_AVAILABLE"
UNKNOWN = "UNKNOWN"
NONE = "NONE"
