/** Finite canonical ontology. Families are operators; instances are parameterized. */

import type { CanonicalConcept, ConceptBreakdown } from "./types";

function c(partial: CanonicalConcept): CanonicalConcept {
  return partial;
}

export const OPERATOR_FAMILIES: CanonicalConcept[] = [
  c({
    id: "ORDINAL_TOUCH",
    displayName: "Ordinal Touch",
    conceptType: "path event",
    category: "population",
    definition: "ORDINAL × TOUCH × PRICE LEVEL. FIRST80 is the implemented instance at first × 80¢.",
    whatItMeans: "A parameterized first/nth close-path touch at a 5¢ grid level.",
    whatItDoesNotMean: [
      "a new locked population for every FIRST55 / SECOND80 combination",
      "an executed fill",
      "compiler acceptance of every generated phrase",
    ],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "phenomenaCatalog FIRST80 + research_vocabulary_v0 FIRST_PRICE_TOUCH",
    relatedConcepts: ["FIRST80", "FIRST_PRICE_TOUCH", "PRICE_E4", "T40"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["FIRST80_Q3"],
    knownFields: ["price_e4", "yes_bid_close"],
    compilerConcept: false,
    whatYouCanDo: "Search any FIRST/SECOND/… × 5–95¢. Only FIRST80 is a locked executable population.",
    whatDataSupports: "Warehouse FIRST80 @ 8000 E4. Other prices are compiler-bindable FIRST_PRICE_TOUCH only.",
  }),
  c({
    id: "DROP_TO",
    displayName: "Drop To Destination",
    conceptType: "path event",
    category: "path",
    definition: "DROP × DESTINATION. DROP40 binds to implemented T40. Other destinations are recognized only.",
    whatItMeans: "A later downward destination on the observed close path.",
    whatItDoesNotMean: ["a stop-loss fill", "generic path DSL at arbitrary levels"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "AUTHORITY_MATRIX path / barrier — T40 only",
    relatedConcepts: ["T40", "EVER_TOUCH", "REVERSAL"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate"],
    templates: ["FIRST80_Q3", "T40_ONLY_PATH"],
    knownFields: ["T40"],
    compilerConcept: false,
    whatYouCanDo: "Recognize drop-to-N language. Execute only T40 on bound FIRST80 populations.",
    whatDataSupports: "barrier_survival_v1 T40 field on FIRST80 / NCAAB_FIRST80_P5.",
  }),
  c({
    id: "BOUNCE_TO",
    displayName: "Bounce To Destination",
    conceptType: "path event",
    category: "path",
    definition: "BOUNCE × DESTINATION. Recognized family. No bounce producer in Phases 0–6.",
    whatItMeans: "An upward destination after a prior move — vocabulary only.",
    whatItDoesNotMean: ["mean-reversion edge", "an implemented recovery lock"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "Authority matrix: generic path DSL ABSENT",
    relatedConcepts: ["RECOVER_TO", "REVERSAL", "WHAT_HAPPENED_NEXT"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Discover the family. Cannot run a bounce measurement.",
    whatDataSupports: "None. NOT_CONSTRUCTIBLE ≠ zero.",
  }),
  c({
    id: "RECOVER_TO",
    displayName: "Recover To Destination",
    conceptType: "path event",
    category: "path",
    definition: "RECOVER × DESTINATION. Distinct from bounce. No recovery producer bound.",
    whatItMeans: "Return toward a stated level after an adverse move.",
    whatItDoesNotMean: ["bounce", "FIRST80 re-touch as a locked second event", "edge"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "Authority matrix: generic path DSL ABSENT",
    relatedConcepts: ["BOUNCE_TO", "WHAT_HAPPENED_NEXT", "FIRST80"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Recognize recover-to-N. Cannot execute it.",
    whatDataSupports: "None.",
  }),
  c({
    id: "REVERSAL",
    displayName: "Directional Reversal",
    conceptType: "path event",
    category: "path",
    definition: "REVERSAL × DIRECTION (UP|DOWN) without requiring a destination.",
    whatItMeans: "Direction-only reversion language.",
    whatItDoesNotMean: ["PRICE_MOVE magnitude", "edge", "a bounce lock"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "research_vocabulary_v0 PRICE_MOVE / BIG_MOVE (magnitude required)",
    relatedConcepts: ["PRICE_MOVE", "BOUNCE_TO", "DROP_TO"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "See the family. PRICE_MOVE still needs explicit magnitude_e4 to compile.",
    whatDataSupports: "None for qualitative reversal.",
  }),
  c({
    id: "CROSS",
    displayName: "Cross / Break / Breach",
    conceptType: "path event",
    category: "price_threshold",
    definition: "CROSS × DIRECTION × LEVEL. TOUCH ≠ CROSS ≠ STATE.",
    whatItMeans: "A directional threshold event, not a first-touch population and not a state.",
    whatItDoesNotMean: ["FIRST80", "being above a level", "a fill"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "Vocabulary doctrine — no distinct cross producer",
    relatedConcepts: ["ORDINAL_TOUCH", "PRICE_STATE", "FIRST_PRICE_TOUCH"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: ["price_e4"],
    compilerConcept: false,
    whatYouCanDo: "Recognize cross language. Do not run it as FIRST80.",
    whatDataSupports: "None as a distinct event.",
  }),
  c({
    id: "PRICE_STATE",
    displayName: "Above / Below State",
    conceptType: "condition",
    category: "price_threshold",
    definition: "STATE × RELATION × LEVEL. A state is not a touch.",
    whatItMeans: "Whether price is above/below/at-least a level at an observation.",
    whatItDoesNotMean: ["FIRST80", "a cross", "T40 (ever-close)"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "No price-state filter in vocabulary compiler",
    relatedConcepts: ["CROSS", "ORDINAL_TOUCH", "SCORE_MARGIN"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: ["yes_bid_close"],
    compilerConcept: false,
    whatYouCanDo: "Discover the distinction. Cannot filter populations by above/below price yet.",
    whatDataSupports: "None as a bound state filter.",
  }),
  c({
    id: "EVER_TOUCH",
    displayName: "Ever Touch",
    conceptType: "path event",
    category: "path",
    definition: "EVER × LEVEL. EVER40 / T40 is implemented. Other levels are recognized only.",
    whatItMeans: "Whether the subsequent path ever prints a close at or beyond the level.",
    whatItDoesNotMean: ["a fill at that level", "terminal outcome"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "STOP_T40 / T40 barrier_survival_v1",
    relatedConcepts: ["T40", "NEVER_TOUCH", "DROP_TO"],
    compatiblePopulations: ["FIRST80", "NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["T40", "HIT40"],
    compilerConcept: false,
    whatYouCanDo: "Run T40 on locked FIRST80 populations. Other ever-levels are not constructible.",
    whatDataSupports: "T40 boolean on FIRST80 artifacts.",
  }),
  c({
    id: "NEVER_TOUCH",
    displayName: "Never Touch / Survive",
    conceptType: "path event",
    category: "path",
    definition: "NEVER × LEVEL. NEVER40 binds to SURVIVE + T40. SURVIVE ≠ TERMINAL YES.",
    whatItMeans: "Absence of a later close at or beyond the stop.",
    whatItDoesNotMean: ["winning the contract", "edge"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "research_vocabulary_v0 SURVIVE / STOP_T40",
    relatedConcepts: ["SURVIVE", "T40", "EVER_TOUCH"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["T40"],
    compilerConcept: false,
    whatYouCanDo: "Survive at 40¢ is implemented. Other never-levels need a producer that does not exist.",
    whatDataSupports: "barrier_survival_v1.",
  }),
  c({
    id: "SEQUENCE",
    displayName: "Event Sequence",
    conceptType: "condition",
    category: "path",
    definition: "EVENT → EVENT → TERMINAL. Recognized composition. Runnable only when every clause is implemented.",
    whatItMeans: "Then / after / before chaining of phenomenon clauses.",
    whatItDoesNotMean: ["a new research_spec invented from English", "Phase 7 portfolio"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "FIRST80_Q3 = FIRST80 → T40 → Kalshi YES/NO",
    relatedConcepts: ["FIRST80", "T40", "TERMINAL_YES", "WHAT_HAPPENED_NEXT"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "See recognized structure. FIRST80→T40→W can be run via locked templates. Bounce/recover tails cannot.",
    whatDataSupports: "FIRST80_Q3 / NCAAB_FIRST80_P5 only for the implemented subsequence.",
  }),
  c({
    id: "TIME_HORIZON",
    displayName: "Time-to-Event Horizon",
    conceptType: "condition",
    category: "time",
    definition: "EVENT_A → EVENT_B with HORIZON = Nm. Recognized. Not constructible.",
    whatItMeans: "A duration constraint between two recognized events.",
    whatItDoesNotMean: ["period_remaining_s / CLOCK_REMAINING", "an implemented timer"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "No intra-event duration producer in Phases 0–6",
    relatedConcepts: ["CLOCK_REMAINING", "SEQUENCE"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Recognize 'within five minutes'. Cannot execute it as a measurement.",
    whatDataSupports: "None.",
  }),
];

export const CANONICAL_CONCEPTS: CanonicalConcept[] = [
  ...OPERATOR_FAMILIES,
  c({
    id: "FIRST80",
    displayName: "FIRST80",
    conceptType: "population",
    category: "population",
    definition: "First authoritative qualifying 80¢ touch. Instance of ORDINAL_TOUCH with ordinal=FIRST, level=80¢.",
    whatItMeans: "FIRST × TOUCH × 80¢ on the tradable yes_bid_close path with quality gates.",
    whatItDoesNotMean: [
      "FIRST75 / FIRST83 / SECOND80",
      "an executed trade at 80¢",
      "terminal YES",
      "edge",
    ],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "measurement_registry FIRST80 warehouse_frozen_v1; phenomenaCatalog",
    relatedConcepts: ["FIRST_PRICE_TOUCH", "ORDINAL_TOUCH", "T40", "PERIOD_Q3", "NCAAB_FIRST80_P5"],
    compatiblePopulations: ["FIRST80", "NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: ["FIRST80_Q3", "NCAAB_FIRST80_P5"],
    knownFields: ["yes_bid_close", "entry_slice", "HIT80"],
    compilerConcept: true,
    whatYouCanDo: "Load FIRST80_Q3 or NCAAB_FIRST80_P5, validate, run t40_rate / kalshi_yes_rate.",
    whatDataSupports: "NBA FIRST80 Q3 n=290; NCAAB FIRST80 P5 n=721 (membership locks).",
  }),
  c({
    id: "FIRST_PRICE_TOUCH",
    displayName: "First Price Touch",
    conceptType: "anchor",
    category: "population",
    definition: "anchor.event = FIRST_PRICE_TOUCH with explicit price_e4.",
    whatItMeans: "The first time the observed close path reaches a stated E4 price.",
    whatItDoesNotMean: ["a locked population at every price", "FILL", "TERMINAL_YES"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 FIRST_PRICE_TOUCH",
    relatedConcepts: ["FIRST80", "ORDINAL_TOUCH", "PRICE_E4"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["price_e4"],
    templates: ["FIRST80_Q3"],
    knownFields: ["price_e4", "price_field", "requires_seen_below"],
    compilerConcept: true,
    whatYouCanDo: "Compiler binds this event when first-price-touch language + explicit cents are present.",
    whatDataSupports: "Locked only as FIRST80. Other prices have no warehouse freeze.",
  }),
  c({
    id: "FIRST83",
    displayName: "FIRST83",
    conceptType: "population",
    category: "population",
    definition: "Would be FIRST_PRICE_TOUCH @ 8300. No Phase 0–6 lock.",
    whatItMeans: "A known missing FIRST83 population.",
    whatItDoesNotMean: ["a silent fallback to FIRST80"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "phenomenaCatalog FIRST83 ABSENT; template FIRST83_Q3 UNAVAILABLE",
    relatedConcepts: ["FIRST80", "ORDINAL_TOUCH"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["FIRST83_Q3"],
    knownFields: ["price_e4"],
    compilerConcept: false,
    whatYouCanDo: "Inspect the gap. Do not invent a population.",
    whatDataSupports: "None.",
  }),
  c({
    id: "NCAAB_FIRST80_P5",
    displayName: "NCAAB FIRST80 P5",
    conceptType: "population",
    category: "sport",
    definition: "P5∩P5 FIRST80. Membership = frozen parquet rows only.",
    whatItMeans: "College basketball FIRST80 restricted to Power Five vs Power Five.",
    whatItDoesNotMean: ["full NCAAB FIRST80", "NBA FIRST80 fallback", "reconstructed P5 filter"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "measurement_registry NCAAB_FIRST80_P5",
    relatedConcepts: ["FIRST80", "P5", "NCAAB"],
    compatiblePopulations: ["NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: ["NCAAB_FIRST80_P5"],
    knownFields: ["entry_slice"],
    compilerConcept: false,
    whatYouCanDo: "Load NCAAB_FIRST80_P5 and run bound measurements.",
    whatDataSupports: "n=721 frozen P5 membership lock.",
  }),
  c({
    id: "T40",
    displayName: "T40",
    conceptType: "path event",
    category: "path",
    definition: "Later tradable close ≤ 40¢. Instance of EVER_TOUCH / DROP_TO at 40.",
    whatItMeans: "Path barrier HIT40=4000 on yes_bid_close. SURVIVE is the complement language.",
    whatItDoesNotMean: [
      "an executed stop at 40¢",
      "guaranteed liquidity",
      "terminal NO",
      "wick-only stop",
    ],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "quality.py HIT40=4000; barrier_survival_v1; STOP_T40",
    relatedConcepts: ["STOP_T40", "SURVIVE", "FIRST80", "EVER_TOUCH", "DROP_TO"],
    compatiblePopulations: ["FIRST80", "NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate"],
    templates: ["FIRST80_Q3", "T40_ONLY_PATH"],
    knownFields: ["T40", "HIT40"],
    compilerConcept: true,
    whatYouCanDo: "Request t40_rate on bound FIRST80 populations.",
    whatDataSupports: "T40 boolean on FIRST80 / NCAAB artifacts.",
  }),
  c({
    id: "STOP_T40",
    displayName: "Stop T40",
    conceptType: "condition",
    category: "path",
    definition: "path_condition EVER_CLOSE_LE @ 4000. Primary = close path ≤ 40¢.",
    whatItMeans: "Compiler synonym family for the 40¢ barrier.",
    whatItDoesNotMean: ["WICK_STOP as primary", "FILL", "TERMINAL_NO"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 STOP_T40",
    relatedConcepts: ["T40", "SURVIVE"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["T40"],
    compilerConcept: true,
    whatYouCanDo: "Compiler binds path_conditions when T40 / stop language is present.",
    whatDataSupports: "barrier_survival_v1.",
  }),
  c({
    id: "SURVIVE",
    displayName: "Survive",
    conceptType: "path event",
    category: "path",
    definition: "NEVER_CLOSE_LE. Absence of later close ≤ stop. Not a win.",
    whatItMeans: "Path survival. Requires explicit stop_price_e4 unless T40 is stated.",
    whatItDoesNotMean: ["TERMINAL_YES", "WON", "EDGE"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 SURVIVE",
    relatedConcepts: ["T40", "NEVER_TOUCH", "TERMINAL_YES"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["T40", "stop_price_e4"],
    compilerConcept: true,
    whatYouCanDo: "Interpret survive language. Pair with T40 for a complete stop.",
    whatDataSupports: "Complement of T40 on bound populations.",
  }),
  c({
    id: "BARRIER_SURVIVAL",
    displayName: "Barrier Survival",
    conceptType: "measurement",
    category: "path",
    definition: "definition_version barrier_survival_v1.",
    whatItMeans: "The implemented path-survival measurement family.",
    whatItDoesNotMean: ["terminal win rate", "edge"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "bindings BARRIER_SURVIVAL_V1",
    relatedConcepts: ["T40", "SURVIVE", "t40_rate"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["T40"],
    compilerConcept: false,
    whatYouCanDo: "Run t40_rate.",
    whatDataSupports: "FIRST80 / NCAAB_FIRST80_P5.",
  }),
  c({
    id: "MAX_ADVERSE_PATH",
    displayName: "Maximum Adverse Path",
    conceptType: "measurement",
    category: "path",
    definition: "Worst observed adverse close excursion. Requires a bound path series.",
    whatItMeans: "Registered drawdown-style path language.",
    whatItDoesNotMean: ["an implemented volatility producer", "edge"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "phenomenaCatalog MAX_ADVERSE_PATH; PATH_VOL_PLACEHOLDER UNAVAILABLE",
    relatedConcepts: ["T40", "WHAT_HAPPENED_NEXT"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["PATH_VOL_PLACEHOLDER"],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "See that drawdown/volatility is not available.",
    whatDataSupports: "None until a path series is bound.",
  }),
  c({
    id: "TERMINAL_YES",
    displayName: "Terminal YES (W)",
    conceptType: "terminal outcome",
    category: "terminal",
    definition: "Kalshi settlement YES. Field W / expiration_result_yes.",
    whatItMeans: "Contract resolves YES. Colloquial 'win' maps here — it is not box-score.",
    whatItDoesNotMean: ["SURVIVE", "box-score home win", "EDGE"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 TERMINAL_YES; warehouse_frozen_v1",
    relatedConcepts: ["SETTLEMENT", "TERMINAL_NO", "kalshi_yes_rate"],
    compatiblePopulations: ["FIRST80", "NCAAB_FIRST80_P5"],
    knownMeasurements: ["kalshi_yes_rate"],
    templates: ["FIRST80_Q3", "TERMINAL_YES_ONLY"],
    knownFields: ["W", "expiration_result_yes"],
    compilerConcept: true,
    whatYouCanDo: "Request kalshi_yes_rate on bound populations.",
    whatDataSupports: "W on FIRST80 artifacts.",
  }),
  c({
    id: "TERMINAL_NO",
    displayName: "Terminal NO",
    conceptType: "terminal outcome",
    category: "terminal",
    definition: "Kalshi settlement NO.",
    whatItMeans: "Contract resolves NO. Colloquial 'loss' maps here.",
    whatItDoesNotMean: ["T40", "SURVIVE", "EDGE"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 TERMINAL_NO",
    relatedConcepts: ["TERMINAL_YES", "SETTLEMENT"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["TERMINAL_NO_ONLY"],
    knownFields: ["W"],
    compilerConcept: true,
    whatYouCanDo: "Compiler can bind KALSHI_NO. Complement of kalshi_yes_rate.",
    whatDataSupports: "W / expiration_result_yes inverted.",
  }),
  c({
    id: "SETTLEMENT",
    displayName: "Settlement",
    conceptType: "terminal outcome",
    category: "terminal",
    definition: "Exchange settlement outcome family.",
    whatItMeans: "Kalshi YES/NO resolution for the bound market.",
    whatItDoesNotMean: ["path survival", "box score"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "phenomenaCatalog SETTLEMENT",
    relatedConcepts: ["TERMINAL_YES", "TERMINAL_NO"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["kalshi_yes_rate"],
    templates: ["TERMINAL_YES_ONLY", "TERMINAL_NO_ONLY"],
    knownFields: ["W"],
    compilerConcept: false,
    whatYouCanDo: "Measure terminal proportions when a population is bound.",
    whatDataSupports: "Kalshi expiration fields.",
  }),
  c({
    id: "PERIOD_Q1",
    displayName: "Q1",
    conceptType: "time bucket",
    category: "time",
    definition: "period / entry_slice = Q1. NBA/WNBA regulation quarter.",
    whatItMeans: "First quarter. Exact clock bucket — not 'early game'.",
    whatItDoesNotMean: ["an official early-game definition"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "research_vocabulary_v0 PERIOD_Q1; clock.py Q1–Q4",
    relatedConcepts: ["PERIOD_Q2", "PERIOD_Q3", "ASKED_SIX"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["FIRST80_Q1"],
    knownFields: ["period", "entry_slice"],
    compilerConcept: true,
    whatYouCanDo: "Compiler can add a Q1 slice. FIRST80_Q1 is structural, not the n=290 lock.",
    whatDataSupports: "NBA/WNBA clock_snap Q1.",
  }),
  c({
    id: "PERIOD_Q2",
    displayName: "Q2",
    conceptType: "time bucket",
    category: "time",
    definition: "period / entry_slice = Q2.",
    whatItMeans: "Second quarter.",
    whatItDoesNotMean: ["halftime as a locked object"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "research_vocabulary_v0 PERIOD_Q2",
    relatedConcepts: ["PERIOD_Q1", "PERIOD_Q3", "ASKED_SIX"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["FIRST80_Q2"],
    knownFields: ["period", "entry_slice"],
    compilerConcept: true,
    whatYouCanDo: "Compiler slice. Structural FIRST80_Q2 template only.",
    whatDataSupports: "NBA/WNBA clock_snap Q2.",
  }),
  c({
    id: "PERIOD_Q3",
    displayName: "Q3",
    conceptType: "time bucket",
    category: "time",
    definition: "period / entry_slice = Q3. Locked FIRST80_Q3 slice.",
    whatItMeans: "Third quarter. The implemented FIRST80 time axis.",
    whatItDoesNotMean: ["late game"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "FIRST80_Q3 warehouse lock n=290",
    relatedConcepts: ["FIRST80", "PERIOD_Q4", "ASKED_SIX"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["period", "entry_slice"],
    compilerConcept: true,
    whatYouCanDo: "Load FIRST80_Q3 and run.",
    whatDataSupports: "entry_slice = Q3 on the frozen NBA FIRST80 ledger.",
  }),
  c({
    id: "PERIOD_Q4",
    displayName: "Q4",
    conceptType: "time bucket",
    category: "time",
    definition: "period = Q4. Exact. Late game is not automatically Q4.",
    whatItMeans: "Fourth quarter.",
    whatItDoesNotMean: ["LATE_GAME"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "research_vocabulary_v0 PERIOD_Q4",
    relatedConcepts: ["LATE_GAME", "PERIOD_Q3"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["FIRST80_Q4"],
    knownFields: ["period", "entry_slice"],
    compilerConcept: true,
    whatYouCanDo: "Compiler can slice Q4. Template is structural.",
    whatDataSupports: "NBA/WNBA clock_snap Q4.",
  }),
  c({
    id: "ASKED_SIX",
    displayName: "Asked-Six",
    conceptType: "structural axis",
    category: "time",
    definition: "ASKED_SIX = {Q2, Q3, H1_2, H2_1}.",
    whatItMeans: "Default mid-game structural slices.",
    whatItDoesNotMean: ["late game", "Q4"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "roller.state.clock.ASKED_SIX 4.1.0-R",
    relatedConcepts: ["PERIOD_Q2", "PERIOD_Q3", "NCAAB_H1_2", "NCAAB_H2_1"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["FIRST80_ASKED_SIX"],
    knownFields: ["entry_slice"],
    compilerConcept: true,
    whatYouCanDo: "Compiler can attach ASKED_SIX as a structural slice set.",
    whatDataSupports: "Clock helper ASKED_SIX.",
  }),
  c({
    id: "NCAAB_H1_1",
    displayName: "H1_1",
    conceptType: "time bucket",
    category: "time",
    definition: "NCAAB early first half (remaining > 600s).",
    whatItMeans: "Authoritative NCAAB entry_slice value.",
    whatItDoesNotMean: ["NBA Q1"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "clock.py entry_slice NCAAB",
    relatedConcepts: ["NCAAB_H1_2", "NCAAB"],
    compatiblePopulations: ["NCAAB_FIRST80_P5"],
    knownMeasurements: [],
    templates: [],
    knownFields: ["entry_slice"],
    compilerConcept: false,
    whatYouCanDo: "NCAAB executor accepts H1_1 as a structural slice.",
    whatDataSupports: "NCAAB half-bucket artifact column.",
  }),
  c({
    id: "NCAAB_H1_2",
    displayName: "H1_2",
    conceptType: "time bucket",
    category: "time",
    definition: "Late first half. Compiler-bindable.",
    whatItMeans: "NCAAB entry_slice H1_2.",
    whatItDoesNotMean: ["NBA second quarter"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 NCAAB_H1_2",
    relatedConcepts: ["NCAAB_H2_1", "ASKED_SIX"],
    compatiblePopulations: ["NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate"],
    templates: ["NCAAB_FIRST80_H1_2"],
    knownFields: ["entry_slice"],
    compilerConcept: true,
    whatYouCanDo: "Compiler binds H1_2. Template is structural unless the P5 run is sliced.",
    whatDataSupports: "NCAAB FIRST80 P5 half buckets.",
  }),
  c({
    id: "NCAAB_H2_1",
    displayName: "H2_1",
    conceptType: "time bucket",
    category: "time",
    definition: "Early second half.",
    whatItMeans: "NCAAB entry_slice H2_1.",
    whatItDoesNotMean: ["NBA Q3"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 NCAAB_H2_1",
    relatedConcepts: ["NCAAB_H1_2", "ASKED_SIX"],
    compatiblePopulations: ["NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate"],
    templates: ["NCAAB_FIRST80_H2_1"],
    knownFields: ["entry_slice"],
    compilerConcept: true,
    whatYouCanDo: "Compiler binds H2_1.",
    whatDataSupports: "NCAAB FIRST80 P5 half buckets.",
  }),
  c({
    id: "NCAAB_H2_2",
    displayName: "H2_2",
    conceptType: "time bucket",
    category: "time",
    definition: "Late second half (remaining ≤ 600s).",
    whatItMeans: "Authoritative NCAAB entry_slice.",
    whatItDoesNotMean: ["Q4"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "clock.py entry_slice NCAAB",
    relatedConcepts: ["NCAAB_H2_1"],
    compatiblePopulations: ["NCAAB_FIRST80_P5"],
    knownMeasurements: [],
    templates: [],
    knownFields: ["entry_slice"],
    compilerConcept: false,
    whatYouCanDo: "Executor accepts H2_2 as a slice on NCAAB P5.",
    whatDataSupports: "NCAAB half-bucket column.",
  }),
  c({
    id: "LATE_GAME",
    displayName: "Late Game",
    conceptType: "condition",
    category: "time",
    definition: "Ambiguous. Requires an explicit late_definition. Not Q4.",
    whatItMeans: "A registered ambiguous time phrase.",
    whatItDoesNotMean: ["PERIOD_Q4", "ASKED_SIX"],
    constructibility: "REGISTERED",
    authoritativeSource: "research_vocabulary_v0 LATE_GAME unresolved_if_ambiguous",
    relatedConcepts: ["PERIOD_Q4", "CLOCK_REMAINING"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Clarify Q4 / last 5m / last 2m. Compiler will not invent a threshold.",
    whatDataSupports: "None until defined.",
  }),
  c({
    id: "CLOCK_REMAINING",
    displayName: "Clock Remaining",
    conceptType: "condition",
    category: "time",
    definition: "period_remaining_s. 'Under five minutes' → lt 300.",
    whatItMeans: "Game-clock remaining in the current period.",
    whatItDoesNotMean: ["time-to-event horizon after FIRST80"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "research_vocabulary_v0 CLOCK_REMAINING",
    relatedConcepts: ["TIME_HORIZON", "LATE_GAME"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["CLOCK_UNDER_5"],
    knownFields: ["period_remaining_s"],
    compilerConcept: true,
    whatYouCanDo: "Compiler binds explicit remaining-seconds rules it already knows.",
    whatDataSupports: "clock_snap remaining.",
  }),
  c({
    id: "OT",
    displayName: "Overtime",
    conceptType: "time bucket",
    category: "time",
    definition: "entry_slice OT exists on the clock helper. No locked OT FIRST80 population.",
    whatItMeans: "A known clock value.",
    whatItDoesNotMean: ["an implemented OT research object"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "clock.py OT; template NBA_OVERTIME_TOUCH UNAVAILABLE",
    relatedConcepts: ["PERIOD_Q4"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["NBA_OVERTIME_TOUCH"],
    knownFields: ["entry_slice"],
    compilerConcept: false,
    whatYouCanDo: "See that OT is a clock label, not a locked population.",
    whatDataSupports: "Clock function only.",
  }),
  c({
    id: "PRICE_E4",
    displayName: "Price (E4)",
    conceptType: "data field",
    category: "price_threshold",
    definition: "Integer E4 cents. 80¢ = 8000. Never float dollars.",
    whatItMeans: "Authoritative price unit. 80% is not automatically 80¢.",
    whatItDoesNotMean: ["implied probability as truth", "fair value", "0.80 dollars as float math"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 PRICE_E4",
    relatedConcepts: ["YES_BID_CLOSE", "HIT80", "HIT40"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["YES_BID_CLOSE_FIELD"],
    knownFields: ["price_e4"],
    compilerConcept: true,
    whatYouCanDo: "Use E4 integers in specs. Search 80c / 80¢ / 0.80 as notation.",
    whatDataSupports: "All FIRST80 price fields.",
  }),
  c({
    id: "YES_BID_CLOSE",
    displayName: "yes_bid_close",
    conceptType: "data field",
    category: "price_threshold",
    definition: "Default FIRST80 price_field. Candle close of the YES bid.",
    whatItMeans: "Observed close path — not last trade, not L2.",
    whatItDoesNotMean: ["FILL", "L2 book", "fair value"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "FIRST_PRICE_TOUCH default_parameters.price_field",
    relatedConcepts: ["CANDLE_1M", "PRICE_E4", "OBSERVABLE_PATH_ONLY"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["YES_BID_CLOSE_FIELD"],
    knownFields: ["yes_bid_close"],
    compilerConcept: false,
    whatYouCanDo: "This is the bound price field for FIRST80.",
    whatDataSupports: "Candle 1m YES bid close.",
  }),
  c({
    id: "HIT80",
    displayName: "HIT80",
    conceptType: "data field",
    category: "price_threshold",
    definition: "HIT80 = 8000 E4 quality constant.",
    whatItMeans: "The 80¢ quality threshold used by FIRST80.",
    whatItDoesNotMean: ["SECOND80", "a fill at 80"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "roller.research.quality HIT80=8000 frozen_v1",
    relatedConcepts: ["FIRST80", "HIT40"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["HIT80_HIT40_PAIR"],
    knownFields: ["HIT80"],
    compilerConcept: false,
    whatYouCanDo: "Treat as the constant behind FIRST80, not a separate population.",
    whatDataSupports: "Quality module + warehouse.",
  }),
  c({
    id: "HIT40",
    displayName: "HIT40",
    conceptType: "data field",
    category: "price_threshold",
    definition: "HIT40 = 4000 E4.",
    whatItMeans: "The 40¢ quality/barrier constant behind T40.",
    whatItDoesNotMean: ["a fill"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "roller.research.quality HIT40=4000",
    relatedConcepts: ["T40", "HIT80"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate"],
    templates: ["HIT80_HIT40_PAIR"],
    knownFields: ["HIT40"],
    compilerConcept: false,
    whatYouCanDo: "Alias discovery for T40.",
    whatDataSupports: "Quality module.",
  }),
  c({
    id: "CANDLE_1M",
    displayName: "1m Candle",
    conceptType: "information",
    category: "point_in_time",
    definition: "information_regime CANDLE_1M. Candle path ≠ fill.",
    whatItMeans: "One-minute candle observation regime.",
    whatItDoesNotMean: ["FILL", "L2", "BOOK"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 CANDLE_1M",
    relatedConcepts: ["OBSERVABLE_PATH_ONLY", "YES_BID_CLOSE"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["CANDLE_1M_REGIME"],
    knownFields: ["information_regime"],
    compilerConcept: true,
    whatYouCanDo: "Compiler can set information_regime.",
    whatDataSupports: "Candle archives — not order-book.",
  }),
  c({
    id: "OBSERVABLE_PATH_ONLY",
    displayName: "Observable Path Only",
    conceptType: "information",
    category: "path",
    definition: "execution_interpretation OBSERVABLE_PATH_ONLY.",
    whatItMeans: "We observe the candle path. We do not claim fills.",
    whatItDoesNotMean: ["EXECUTION_VALIDATED", "FILL"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 OBSERVABLE_PATH_ONLY",
    relatedConcepts: ["CANDLE_1M"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["CANDLE_1M_REGIME"],
    knownFields: ["execution_interpretation"],
    compilerConcept: true,
    whatYouCanDo: "Compiler can set the interpretation flag.",
    whatDataSupports: "Doctrine + spec field.",
  }),
  c({
    id: "POINT_IN_TIME",
    displayName: "Point-in-Time I(t)",
    conceptType: "information",
    category: "point_in_time",
    definition: "I(t) = { x | available_at(x) < t }. Half-open.",
    whatItMeans: "Only facts available before as_of. Lookahead is forbidden.",
    whatItDoesNotMean: ["what is convenient now", "future labels inside O_t"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "ROLLER/roller/point_in_time public_filter 4.0.0-C",
    relatedConcepts: ["OBSERVATION_TIME", "AVAILABLE_INFORMATION"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["POINT_IN_TIME_INSPECT"],
    knownFields: ["as_of", "available_at"],
    compilerConcept: false,
    whatYouCanDo: "Use Explorer as_of. Do not pull future information.",
    whatDataSupports: "PIT filters on the object inspector.",
  }),
  c({
    id: "OBSERVATION_TIME",
    displayName: "Observation Time O_t",
    conceptType: "anchor",
    category: "point_in_time",
    definition: "anchor.event = OBSERVATION_TIME. assemble_observation.",
    whatItMeans: "A chosen instant. Must not include labels / FIRST80 / Greeks automatically.",
    whatItDoesNotMean: ["FIRST_PRICE_TOUCH", "EDGE"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research_vocabulary_v0 OBSERVATION_TIME; state 2.0.0",
    relatedConcepts: ["POINT_IN_TIME", "AVAILABLE_INFORMATION"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["OBSERVATION_TIME_BASE"],
    knownFields: ["O_t"],
    compilerConcept: true,
    whatYouCanDo: "Inspect O_t in Explorer.",
    whatDataSupports: "assemble_observation.",
  }),
  c({
    id: "AVAILABLE_INFORMATION",
    displayName: "Available Information",
    conceptType: "information",
    category: "point_in_time",
    definition: "What could have been known — information_set on the spec.",
    whatItMeans: "The historical information set, not a reconstructed present.",
    whatItDoesNotMean: ["future settlement leaked into O_t"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "phenomenaCatalog AVAILABLE_INFORMATION",
    relatedConcepts: ["POINT_IN_TIME", "OBSERVATION_TIME"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["CANDLE_1M_REGIME"],
    knownFields: ["information_regime", "information_set"],
    compilerConcept: false,
    whatYouCanDo: "Keep as_of honest.",
    whatDataSupports: "Information regime fields.",
  }),
  c({
    id: "LOOKAHEAD_BIAS",
    displayName: "Lookahead Bias",
    conceptType: "research language",
    category: "point_in_time",
    definition: "Using x with available_at(x) ≥ t. Forbidden by I(t).",
    whatItMeans: "A doctrine term for violating the half-open cut.",
    whatItDoesNotMean: ["a measurement you can request"],
    constructibility: "REGISTERED",
    authoritativeSource: "I(t) contract 4.0.0-C",
    relatedConcepts: ["POINT_IN_TIME"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: ["available_at"],
    compilerConcept: false,
    whatYouCanDo: "Use it to find PIT docs. Not executable.",
    whatDataSupports: "Doctrine only.",
  }),
  c({
    id: "t40_rate",
    displayName: "t40_rate",
    conceptType: "measurement",
    category: "measurement",
    definition: "PATH_PROPORTION of T40 == true. MEASUREMENT ≠ EDGE.",
    whatItMeans: "Empirical frequency of the 40¢ barrier on a bound population.",
    whatItDoesNotMean: ["win rate", "edge", "EV"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "measurement_registry t40_rate IMPLEMENTED",
    relatedConcepts: ["T40", "kalshi_yes_rate", "EMPIRICAL_PROPORTION"],
    compatiblePopulations: ["FIRST80", "NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["T40"],
    compilerConcept: false,
    whatYouCanDo: "Request on FIRST80 / NCAAB_FIRST80_P5 specs.",
    whatDataSupports: "T40 field.",
  }),
  c({
    id: "kalshi_yes_rate",
    displayName: "kalshi_yes_rate",
    conceptType: "measurement",
    category: "measurement",
    definition: "TERMINAL_PROPORTION of Kalshi YES. Not box-score.",
    whatItMeans: "Share of bound observations that settle YES.",
    whatItDoesNotMean: ["edge", "survive rate"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "measurement_registry kalshi_yes_rate IMPLEMENTED",
    relatedConcepts: ["TERMINAL_YES", "t40_rate"],
    compatiblePopulations: ["FIRST80", "NCAAB_FIRST80_P5"],
    knownMeasurements: ["kalshi_yes_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["W"],
    compilerConcept: false,
    whatYouCanDo: "Request on bound FIRST80 families.",
    whatDataSupports: "W / expiration_result_yes.",
  }),
  c({
    id: "FUNDAMENTAL_F_T",
    displayName: "F_t",
    conceptType: "measurement",
    category: "measurement",
    definition: "Prior-only fundamental estimate 4.0.0-A. F_t ≠ true probability ≠ edge.",
    whatItMeans: "Registered observation-time measurement. No bulk population producer in Phase 5.",
    whatItDoesNotMean: ["TRUE_PROBABILITY", "EDGE", "MARKET_PRICE"],
    constructibility: "REGISTERED",
    authoritativeSource: "measurement_registry fundamental REGISTERED_NOT_EXECUTABLE",
    relatedConcepts: ["BASIS", "OBSERVATION_TIME"],
    compatiblePopulations: [],
    knownMeasurements: ["fundamental_f_t"],
    templates: ["FUNDAMENTAL_FT_AT_OT"],
    knownFields: ["F_t"],
    compilerConcept: true,
    whatYouCanDo: "Inspect the concept. Cannot treat a listed route as executable.",
    whatDataSupports: "No bulk producer.",
  }),
  c({
    id: "BASIS",
    displayName: "Basis",
    conceptType: "measurement",
    category: "measurement",
    definition: "Market–fundamental basis 4.0.0-B. BASIS ≠ EDGE.",
    whatItMeans: "Registered V4B measurement.",
    whatItDoesNotMean: ["EDGE", "ALPHA"],
    constructibility: "REGISTERED",
    authoritativeSource: "measurement_registry market_fundamental_basis REGISTERED_NOT_EXECUTABLE",
    relatedConcepts: ["FUNDAMENTAL_F_T", "RESIDUAL"],
    compatiblePopulations: [],
    knownMeasurements: ["basis"],
    templates: ["BASIS_EXTREME_AT_OBSERVATION"],
    knownFields: ["basis"],
    compilerConcept: true,
    whatYouCanDo: "Discover the term. Not an executable bulk route.",
    whatDataSupports: "No bulk producer.",
  }),
  c({
    id: "RESIDUAL",
    displayName: "Residual",
    conceptType: "measurement",
    category: "measurement",
    definition: "V3 response residual. Residual ≠ edge.",
    whatItMeans: "Registered measurement.",
    whatItDoesNotMean: ["EDGE"],
    constructibility: "REGISTERED",
    authoritativeSource: "measurement_registry residual REGISTERED_NOT_EXECUTABLE",
    relatedConcepts: ["BASIS", "DELTA_MARKET"],
    compatiblePopulations: [],
    knownMeasurements: ["residual"],
    templates: ["RESIDUAL_RESPONSE"],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Inspect. Not executable as a FIRST80 measurement.",
    whatDataSupports: "No bulk producer.",
  }),
  c({
    id: "DELTA_MARKET",
    displayName: "Market Delta",
    conceptType: "measurement",
    category: "measurement",
    definition: "Empirical market delta. Δ ≠ EDGE.",
    whatItMeans: "Registered V4B name.",
    whatItDoesNotMean: ["EDGE"],
    constructibility: "REGISTERED",
    authoritativeSource: "research_vocabulary_v0 DELTA_MARKET",
    relatedConcepts: ["GAMMA_DISCRETE", "THETA_OBSERVED"],
    compatiblePopulations: [],
    knownMeasurements: ["market_delta_1m"],
    templates: ["MARKET_DELTA_1M"],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Discover. Not a FIRST80 executor route.",
    whatDataSupports: "No Phase 5 handler.",
  }),
  c({
    id: "GAMMA_DISCRETE",
    displayName: "Discrete Gamma",
    conceptType: "measurement",
    category: "measurement",
    definition: "Empirical discrete gamma. Γ ≠ EDGE.",
    whatItMeans: "Registered V4B name.",
    whatItDoesNotMean: ["EDGE"],
    constructibility: "REGISTERED",
    authoritativeSource: "research_vocabulary_v0 GAMMA_DISCRETE",
    relatedConcepts: ["DELTA_MARKET", "THETA_OBSERVED"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Discover.",
    whatDataSupports: "No Phase 5 handler.",
  }),
  c({
    id: "THETA_OBSERVED",
    displayName: "Observed Theta",
    conceptType: "measurement",
    category: "measurement",
    definition: "Empirical observed theta. Θ ≠ EDGE.",
    whatItMeans: "Registered V4B name.",
    whatItDoesNotMean: ["EDGE"],
    constructibility: "REGISTERED",
    authoritativeSource: "research_vocabulary_v0 THETA_OBSERVED",
    relatedConcepts: ["DELTA_MARKET"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Discover.",
    whatDataSupports: "No Phase 5 handler.",
  }),
  c({
    id: "PRICE_MOVE",
    displayName: "Price Move",
    conceptType: "anchor",
    category: "price_threshold",
    definition: "Requires explicit direction and magnitude_e4. 'Sharply' does not set magnitude.",
    whatItMeans: "A stated move, not a qualitative vibe.",
    whatItDoesNotMean: ["EDGE", "BIG_MOVE as a number"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "research_vocabulary_v0 PRICE_MOVE",
    relatedConcepts: ["BIG_MOVE", "REVERSAL"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["LARGE_DOWN_MOVE_Q4"],
    knownFields: ["magnitude_e4"],
    compilerConcept: true,
    whatYouCanDo: "Compiler binds PRICE_MOVE when magnitude is explicit (e.g. down 15 cents).",
    whatDataSupports: "None until magnitude is filled.",
  }),
  c({
    id: "BIG_MOVE",
    displayName: "Big Move",
    conceptType: "anchor",
    category: "price_threshold",
    definition: "Qualitative. unresolved_if_ambiguous. No approved threshold.",
    whatItMeans: "Known phrase that must not become a silent 10¢ rule.",
    whatItDoesNotMean: ["an invented sigma cut"],
    constructibility: "REGISTERED",
    authoritativeSource: "research_vocabulary_v0 BIG_MOVE",
    relatedConcepts: ["PRICE_MOVE"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["LARGE_DOWN_MOVE_Q4"],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Clarify an E4 threshold. Compiler will leave magnitude unresolved.",
    whatDataSupports: "None.",
  }),
  c({
    id: "EDGE",
    displayName: "Edge",
    conceptType: "research language",
    category: "other",
    definition: "Not an empirical measurement. Terminal must not invent edge.",
    whatItMeans: "A forbidden collapse target for Δ, Γ, Θ, basis, residual, path rates.",
    whatItDoesNotMean: ["t40_rate", "kalshi_yes_rate", "basis"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "research_vocabulary_v0 EDGE; AUTHORITY_MATRIX",
    relatedConcepts: ["BASIS", "DELTA_MARKET", "t40_rate"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Read the refusal. Run measurements instead.",
    whatDataSupports: "None — ABSENT as a Greek.",
  }),
  c({
    id: "WHAT_HAPPENED_NEXT",
    displayName: "What Happened Next",
    conceptType: "research language",
    category: "path",
    definition: "Requires explicit measurement_requests. Not a trade.",
    whatItMeans: "Forward-path language that stays unresolved until measurements are named.",
    whatItDoesNotMean: ["EDGE", "BACKTEST_PROFIT"],
    constructibility: "REGISTERED",
    authoritativeSource: "research_vocabulary_v0 WHAT_HAPPENED_NEXT",
    relatedConcepts: ["SEQUENCE", "T40", "BOUNCE_TO"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Name T40 / terminal / a registered measurement. Do not run 'then what' raw.",
    whatDataSupports: "None until specified.",
  }),
  c({
    id: "FAVORITE",
    displayName: "Favorite",
    conceptType: "condition",
    category: "other",
    definition: "Ambiguous. favorite_definition required.",
    whatItMeans: "Registered phrase — not a default 60¢ rule.",
    whatItDoesNotMean: ["an invented pregame favorite"],
    constructibility: "REGISTERED",
    authoritativeSource: "research_vocabulary_v0 FAVORITE",
    relatedConcepts: ["PRICE_E4"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: true,
    whatYouCanDo: "Clarify the definition. Compiler will not invent one.",
    whatDataSupports: "None.",
  }),
  c({
    id: "SCORE_MARGIN",
    displayName: "Score Margin",
    conceptType: "condition",
    category: "other",
    definition: "state_filters.score_margin requires an explicit value_or_range.",
    whatItMeans: "Lead / trail language without a number stays unresolved.",
    whatItDoesNotMean: ["an invented 5-point cut"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "research_vocabulary_v0 SCORE_MARGIN",
    relatedConcepts: ["PERIOD_Q3"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["MARGIN_LEAD_Q3"],
    knownFields: ["score_margin"],
    compilerConcept: true,
    whatYouCanDo: "Supply an explicit margin.",
    whatDataSupports: "Clock/score snap when present.",
  }),
  c({
    id: "NBA",
    displayName: "NBA",
    conceptType: "sport",
    category: "sport",
    definition: "BBALL1 sport. FIRST80 warehouse lock lives here.",
    whatItMeans: "Professional basketball in the BBALL1 universe.",
    whatItDoesNotMean: ["WNBA", "NCAAB", "MLB FIRST01"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "universes BBALL1 sports",
    relatedConcepts: ["FIRST80", "WNBA", "NCAAB"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: ["period"],
    compilerConcept: false,
    whatYouCanDo: "Run NBA FIRST80_Q3.",
    whatDataSupports: "NBA FIRST80 ledger.",
  }),
  c({
    id: "NCAAB",
    displayName: "NCAAB",
    conceptType: "sport",
    category: "sport",
    definition: "College basketball. Default research binding is P5∩P5.",
    whatItMeans: "NCAA men's basketball in BBALL1.",
    whatItDoesNotMean: ["full-universe NCAAB FIRST80 as the V1 default"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "Phase 6 NCAAB_FIRST80_P5",
    relatedConcepts: ["NCAAB_FIRST80_P5", "P5"],
    compatiblePopulations: ["NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: ["NCAAB_FIRST80_P5"],
    knownFields: ["entry_slice"],
    compilerConcept: false,
    whatYouCanDo: "Load NCAAB_FIRST80_P5.",
    whatDataSupports: "Frozen P5 parquet.",
  }),
  c({
    id: "WNBA",
    displayName: "WNBA",
    conceptType: "sport",
    category: "sport",
    definition: "WNBA is in BBALL1. No Phase 0–6 executable FIRST80 route.",
    whatItMeans: "Women's professional basketball — structural templates only.",
    whatItDoesNotMean: ["NBA FIRST80"],
    constructibility: "REGISTERED",
    authoritativeSource: "templateCatalog WNBA_FIRST80_Q3 STRUCTURAL",
    relatedConcepts: ["NBA", "FIRST80"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["WNBA_FIRST80_Q3"],
    knownFields: ["period"],
    compilerConcept: false,
    whatYouCanDo: "See structural starting points. Cannot run a WNBA FIRST80 lock.",
    whatDataSupports: "No frozen WNBA FIRST80 binding.",
  }),
  c({
    id: "MLB",
    displayName: "MLB",
    conceptType: "sport",
    category: "sport",
    definition: "MLB FIRST01 lives in research-replay. Different sport/semantics. Not BBALL1.",
    whatItMeans: "Baseball is out of this terminal's FIRST80 universe.",
    whatItDoesNotMean: ["FIRST80"],
    constructibility: "NOT_CONSTRUCTIBLE",
    authoritativeSource: "AUTHORITY_MATRIX MLB FIRST01 NO for BBALL1",
    relatedConcepts: [],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["MLB_FIRST01_STUB"],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Do not bind MLB FIRST01 to BBALL1.",
    whatDataSupports: "None in this terminal.",
  }),
  c({
    id: "P5",
    displayName: "Power Five",
    conceptType: "structural axis",
    category: "sport",
    definition: "NCAAB P5∩P5 membership freeze.",
    whatItMeans: "Major-conference vs major-conference filter on NCAAB FIRST80.",
    whatItDoesNotMean: ["reconstructed from team names at query time"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "NCAAB_FIRST80_P5 frozen parquet",
    relatedConcepts: ["NCAAB", "NCAAB_FIRST80_P5"],
    compatiblePopulations: ["NCAAB_FIRST80_P5"],
    knownMeasurements: ["t40_rate"],
    templates: ["P5_VS_P5_ONLY"],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "The lock is the parquet. Do not rebuild P5.",
    whatDataSupports: "Frozen membership rows.",
  }),
  c({
    id: "BBALL1",
    displayName: "BBALL1",
    conceptType: "population",
    category: "sport",
    definition: "Basketball research universe. FIRST80 is one object inside it.",
    whatItMeans: "NBA / WNBA / NCAAB container. Not a portfolio.",
    whatItDoesNotMean: ["Phase 7 multi-object portfolio"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "terminal_api /universes",
    relatedConcepts: ["NBA", "NCAAB", "WNBA"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: ["BBALL1_UNIVERSE"],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Explore games under as_of.",
    whatDataSupports: "Explorer universe listing.",
  }),
  c({
    id: "EMPIRICAL_PROPORTION",
    displayName: "Empirical Proportion",
    conceptType: "research language",
    category: "mathematics",
    definition: "Finite-sample frequency. Implemented as t40_rate / kalshi_yes_rate kinds.",
    whatItMeans: "count / n on a bound population. Not a probability model.",
    whatItDoesNotMean: ["edge", "true probability", "confidence interval (not implemented)"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "measurement kinds PATH_PROPORTION / TERMINAL_PROPORTION",
    relatedConcepts: ["t40_rate", "kalshi_yes_rate", "FINITE_SAMPLE"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Read rates as finite-sample proportions.",
    whatDataSupports: "Bound FIRST80 measurements.",
  }),
  c({
    id: "FINITE_SAMPLE",
    displayName: "Finite Sample",
    conceptType: "research language",
    category: "mathematics",
    definition: "n is the denominator. FIRST80_Q3 n=290 is a lock, not a suggestion.",
    whatItMeans: "Every rate has a countable population.",
    whatItDoesNotMean: ["asymptotic CI as an implemented measurement"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "FIRST80 membership locks",
    relatedConcepts: ["EMPIRICAL_PROPORTION", "FIRST80"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Read n on Results. Do not invent a CI producer.",
    whatDataSupports: "Population n on execute payloads.",
  }),
  c({
    id: "CONDITIONAL",
    displayName: "Conditional",
    conceptType: "research language",
    category: "mathematics",
    definition: "A slice / state_filter on a population. Conditional ≠ new population invented in UI.",
    whatItMeans: "P(measurement | slice) only when the slice is an authoritative axis.",
    whatItDoesNotMean: ["an automatic joint model"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "research_spec state_filters / structural slices",
    relatedConcepts: ["PERIOD_Q3", "SEQUENCE", "JOINT"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: [],
    knownFields: ["entry_slice", "period"],
    compilerConcept: false,
    whatYouCanDo: "Use implemented axes (Q3, T40, terminal). Other conditionals stay structural.",
    whatDataSupports: "Slice filters on locked populations.",
  }),
  c({
    id: "JOINT",
    displayName: "Joint",
    conceptType: "research language",
    category: "mathematics",
    definition: "Joint of implemented clauses (e.g. FIRST80 ∩ Q3 ∩ T40).",
    whatItMeans: "Composition of authoritative bindings — not a new object type.",
    whatItDoesNotMean: ["a fabricated cross-tab for unconstructible clauses"],
    constructibility: "CONFIGURABLE",
    authoritativeSource: "FIRST80_Q3 path+terminal pairing",
    relatedConcepts: ["CONDITIONAL", "MARGINAL", "SEQUENCE"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Run the locked joint. Do not invent FIRST80∩BOUNCE70.",
    whatDataSupports: "FIRST80_Q3.",
  }),
  c({
    id: "MARGINAL",
    displayName: "Marginal",
    conceptType: "research language",
    category: "mathematics",
    definition: "A single implemented measurement over the bound population.",
    whatItMeans: "t40_rate is a marginal path proportion on FIRST80.",
    whatItDoesNotMean: ["edge"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "t40_rate / kalshi_yes_rate",
    relatedConcepts: ["JOINT", "EMPIRICAL_PROPORTION"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: ["t40_rate", "kalshi_yes_rate"],
    templates: ["FIRST80_Q3"],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Read the implemented rates.",
    whatDataSupports: "Executor measurements.",
  }),
  c({
    id: "STATE_SPACE",
    displayName: "State Space",
    conceptType: "research language",
    category: "mathematics",
    definition: "Empirical partitions actually available on a result — not a hypothetical grid.",
    whatItMeans: "Q1–Q4 / T40 / W are axes only when bound.",
    whatItDoesNotMean: ["every grammar family is an available axis"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "Results empirical tree / FIRST80 fields",
    relatedConcepts: ["CONDITIONAL", "PERIOD_Q3", "T40"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: [],
    knownFields: ["entry_slice", "T40", "W"],
    compilerConcept: false,
    whatYouCanDo: "Inspect implemented partitions on Results — this dictionary only names them.",
    whatDataSupports: "FIRST80 artifact fields.",
  }),
  c({
    id: "PROVENANCE",
    displayName: "Provenance",
    conceptType: "evidence",
    category: "evidence",
    definition: "definition_versions + artifacts + fingerprints. Append-only honesty.",
    whatItMeans: "Where a measurement came from.",
    whatItDoesNotMean: ["a new dataset invented in the UI"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "research execute provenance payload",
    relatedConcepts: ["DEFINITION_VERSION", "ARTIFACT", "VALIDATION"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: ["PROVENANCE_AUDIT"],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Read Audit / evidence on a run.",
    whatDataSupports: "Executor provenance blocks.",
  }),
  c({
    id: "DEFINITION_VERSION",
    displayName: "Definition Version",
    conceptType: "evidence",
    category: "evidence",
    definition: "warehouse_frozen_v1 / barrier_survival_v1 / ncaab_first80_p5_v1 / …",
    whatItMeans: "The binding that makes a number authoritative.",
    whatItDoesNotMean: ["a UI label you can edit into a new math"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "AUTHORITY_MATRIX definition_version column",
    relatedConcepts: ["PROVENANCE", "FIRST80"],
    compatiblePopulations: ["FIRST80"],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Declare exactly one FIRST80 definition_version.",
    whatDataSupports: "Spec bindings.",
  }),
  c({
    id: "ARTIFACT",
    displayName: "Artifact",
    conceptType: "evidence",
    category: "evidence",
    definition: "candidates.json / trades.parquet / NCAAB frozen parquet.",
    whatItMeans: "The file-level evidence behind a population.",
    whatItDoesNotMean: ["live Kalshi"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "measurement_registry artifacts[]",
    relatedConcepts: ["PROVENANCE"],
    compatiblePopulations: ["FIRST80", "NCAAB_FIRST80_P5"],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Cite artifacts on results.",
    whatDataSupports: "Frozen warehouse files.",
  }),
  c({
    id: "VALIDATION",
    displayName: "Validation",
    conceptType: "evidence",
    category: "evidence",
    definition: "RUNNABLE / UNRESOLVED / INVALID. RUN requires CURRENT+RUNNABLE.",
    whatItMeans: "Structural check of a research_spec.",
    whatItDoesNotMean: ["a successful fill", "an edge test"],
    constructibility: "IMPLEMENTED",
    authoritativeSource: "POST /research-objects/validate",
    relatedConcepts: ["PROVENANCE"],
    compatiblePopulations: [],
    knownMeasurements: [],
    templates: [],
    knownFields: [],
    compilerConcept: false,
    whatYouCanDo: "Validate before run.",
    whatDataSupports: "Adapter validation.",
  }),
];

export const CONCEPT_BY_ID: Record<string, CanonicalConcept> = Object.fromEntries(
  CANONICAL_CONCEPTS.map((x) => [x.id, x]),
);

export const FIRST80_BREAKDOWN: ConceptBreakdown = {
  conceptId: "FIRST80",
  axes: [
    {
      id: "TIME",
      label: "Time",
      values: [
        { id: "Q3", label: "Q3", availability: "AVAILABLE_NOW", note: "FIRST80_Q3 n=290", relatedConcept: "PERIOD_Q3" },
        { id: "Q1", label: "Q1", availability: "REGISTERED_NOT_CONSTRUCTIBLE", note: "structural FIRST80_Q1", relatedConcept: "PERIOD_Q1" },
        { id: "Q2", label: "Q2", availability: "REGISTERED_NOT_CONSTRUCTIBLE", note: "structural FIRST80_Q2", relatedConcept: "PERIOD_Q2" },
        { id: "Q4", label: "Q4", availability: "REGISTERED_NOT_CONSTRUCTIBLE", note: "Q4 ≠ late game", relatedConcept: "PERIOD_Q4" },
        { id: "OT", label: "OT", availability: "NOT_CURRENTLY_KNOWN", note: "clock label only", relatedConcept: "OT" },
      ],
    },
    {
      id: "PATH",
      label: "Path",
      values: [
        { id: "T40", label: "T40", availability: "AVAILABLE_NOW", relatedConcept: "T40" },
        { id: "BOUNCE", label: "Bounce / recover destinations", availability: "NOT_CURRENTLY_KNOWN", relatedConcept: "BOUNCE_TO" },
      ],
    },
    {
      id: "TERMINAL",
      label: "Terminal",
      values: [
        { id: "YES", label: "YES (W)", availability: "AVAILABLE_NOW", relatedConcept: "TERMINAL_YES" },
        { id: "NO", label: "NO", availability: "AVAILABLE_NOW", relatedConcept: "TERMINAL_NO" },
      ],
    },
    {
      id: "SPORT",
      label: "Sport",
      values: [
        { id: "NBA", label: "NBA", availability: "AVAILABLE_NOW", relatedConcept: "NBA" },
        { id: "NCAAB", label: "NCAAB P5", availability: "AVAILABLE_NOW", relatedConcept: "NCAAB_FIRST80_P5" },
        { id: "WNBA", label: "WNBA", availability: "REGISTERED_NOT_CONSTRUCTIBLE", relatedConcept: "WNBA" },
      ],
    },
  ],
};

export function breakdownFor(id: string): ConceptBreakdown | undefined {
  if (id === "FIRST80" || id === "ORDINAL_TOUCH" || id === "FIRST_PRICE_TOUCH") return FIRST80_BREAKDOWN;
  return undefined;
}

export function implementedConceptIds(): string[] {
  return CANONICAL_CONCEPTS.filter((c) => c.constructibility === "IMPLEMENTED").map((c) => c.id);
}
