"""Base TE versions. Do not collide with research_query CODE_VERSION."""

SEMANTICS_VERSION = "1.0.0"
SCHEMA_VERSION = "1.0.0"
CODE_VERSION = "base_te_v1.0.0"
ENTRY_PRICE_DEFINITION = "tradable_yes_bid_close"
SCORE_VOL_ID = "SCORE_PATH_VOLATILITY_V1"
MARKET_VOL_ID = "MARKET_PRICE_VOLATILITY_V1"
MARKET_VOL_MIN_BARS = 3
MARKET_VOL_RECENT_DIFFS = 5
MARKET_VOL_RECENT_MIN_DIFFS = 3
SCORE_VOL_MIN_INCREMENTS = 3
