"""MOMENTO DYNAMIC RISK ENGINE V5 — offline research only.

Conditional FIRST-80 payoff surfaces. No action optimizer. No live orders.
CANDLE PATH ≠ ACTUAL FILL
FORWARD DISTRIBUTION ≠ TRADABLE EDGE
CONDITIONAL ALPHA ≠ EXECUTABLE ACTION
LIVE DEPLOYMENT: NOT AUTHORIZED
"""
