"""A1 Hybrid Hedge Optimization — research only.

LIVE EXECUTION CHANGED: FALSE.
PRICE EVENT ≠ EXECUTION EVENT.
NCAAB working universe = P5 vs P5.
"""

PROGRAM = "A1_HYBRID_HEDGE_V1"
UNIVERSE_VERSION = "A1_UNIVERSE_V1"
DATASET_VERSION = "FIRST80_V3OPP_V4LEDGER_2025_2026"
LABEL = "OBSERVABLE EXECUTION CONFIDENCE — NOT CONFIRMED FILL"
